version: '2.1'
services:
  identity-provider:
    build:
      context: ./identityProvider
      dockerfile: Dockerfile
    ports:
      - '4000:8080'
    environment:
      WEB3_PROVIDER: 'http://ganache:8545'
      # this needs to change when contracts change
      RBAC_ADDRESS: '0xb61752bb7c6e865037995334848276b53c4688c8'
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: ganache-cli --blockTime=2 --account="0x275AA504F6C89A95A5A0742DF03BF656E496538498986C318EE72C2D190FE77D,100000000000000000000" --mnemonic "album wire record stuff abandon mesh museum piece bean allow refuse below"
  ganache-deploy:
    build:
      context: ./rbac
      dockerfile: Dockerfile
    healthcheck:
      test: curl -sf -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://ganache:8545
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./rbac/build:/usr/src/app/build
  block-explorer:
    image: alethio/ethereum-lite-explorer
    environment:
      APP_NODE_URL: http://localhost:8545
    ports:
      - '7000:80'
